version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on: [ redis, db ]

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
