"""'trans_nul'

Revision ID: 02d13191d0a1
Revises: 6b289c511e37
Create Date: 2024-02-24 19:53:36.452261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02d13191d0a1'
down_revision: Union[str, None] = '6b289c511e37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_pics', 'original_pic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_pics', 'original_pic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
