"""additionaltask

Revision ID: 1a000bc3e423
Revises: 62573d4bc2b6
Create Date: 2024-02-21 17:13:50.616380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a000bc3e423'
down_revision: Union[str, None] = '62573d4bc2b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userprofile', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'userprofile', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userprofile', type_='foreignkey')
    op.drop_column('userprofile', 'user_id')
    # ### end Alembic commands ###
