"""2302_ending_09

Revision ID: 41ab3a491b10
Revises: c8687212ab82
Create Date: 2024-02-23 16:41:45.265904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ab3a491b10'
down_revision: Union[str, None] = 'c8687212ab82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tag_association',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_constraint('comments_images_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'images_id')
    op.drop_constraint('tags_iamges_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'iamges_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('iamges_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_iamges_id_fkey', 'tags', 'images', ['iamges_id'], ['id'])
    op.add_column('comments', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_images_id_fkey', 'comments', 'images', ['images_id'], ['id'])
    op.drop_table('image_tag_association')
    # ### end Alembic commands ###
