"""additionaltask3

Revision ID: 5c3ffefec0da
Revises: 6a080abed9e2
Create Date: 2024-02-21 08:27:23.192221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3ffefec0da'
down_revision: Union[str, None] = '6a080abed9e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userprofile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('photoloadedcount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('users', 'photoloadedcount')
    op.drop_column('users', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_info', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('photoloadedcount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_table('userprofile')
    # ### end Alembic commands ###
