"""2302_ending_02

Revision ID: 5eea53e81514
Revises: d2cdb0fb5e2d
Create Date: 2024-02-23 15:16:31.323693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eea53e81514'
down_revision: Union[str, None] = 'd2cdb0fb5e2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
