"""2502_ending_00

Revision ID: 61be8d6904e2
Revises: 545f9fa76dc4
Create Date: 2024-02-24 22:02:49.515395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61be8d6904e2'
down_revision: Union[str, None] = '545f9fa76dc4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_pics', 'original_pic_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_pics', 'original_pic_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
