"""2302_ending_11

Revision ID: 644e7d812317
Revises: dd66cf5f1b8e
Create Date: 2024-02-23 16:57:33.079586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '644e7d812317'
down_revision: Union[str, None] = 'dd66cf5f1b8e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_tag_association',
    sa.Column('image_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.drop_constraint('comments_images_id_fkey', 'comments', type_='foreignkey')
    op.drop_column('comments', 'images_id')
    op.drop_constraint('tags_images_id_fkey', 'tags', type_='foreignkey')
    op.drop_column('tags', 'images_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tags', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('tags_images_id_fkey', 'tags', 'images', ['images_id'], ['id'])
    op.add_column('comments', sa.Column('images_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('comments_images_id_fkey', 'comments', 'images', ['images_id'], ['id'])
    op.drop_table('image_tag_association')
    # ### end Alembic commands ###
