"""additionaltask2

Revision ID: 6a080abed9e2
Revises: ae022751a1bf
Create Date: 2024-02-21 08:08:07.215392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a080abed9e2'
down_revision: Union[str, None] = 'ae022751a1bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('additional_info', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'additional_info')
    # ### end Alembic commands ###
