"""2302_ending_06

Revision ID: 72d9fa6201ea
Revises: 00984a3a63a3
Create Date: 2024-02-23 16:25:02.562139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72d9fa6201ea'
down_revision: Union[str, None] = '00984a3a63a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('images_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'images', ['images_id'], ['id'])
    op.add_column('tags', sa.Column('iamges_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'images', ['iamges_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'iamges_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'images_id')
    # ### end Alembic commands ###
