"""additionaltask1

Revision ID: db1f53e7a33a
Revises: 4b366051ef76
Create Date: 2024-02-20 22:41:01.545417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db1f53e7a33a'
down_revision: Union[str, None] = '4b366051ef76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photoloadedcount', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photoloadedcount')
    # ### end Alembic commands ###
