"""2302_ending_10

Revision ID: dd66cf5f1b8e
Revises: 41ab3a491b10
Create Date: 2024-02-23 16:50:13.101876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd66cf5f1b8e'
down_revision: Union[str, None] = '41ab3a491b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_tag_association')
    op.add_column('comments', sa.Column('images_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'images', ['images_id'], ['id'])
    op.add_column('tags', sa.Column('images_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tags', 'images', ['images_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'images_id')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'images_id')
    op.create_table('image_tag_association',
    sa.Column('image_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], name='image_tag_association_image_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='image_tag_association_tag_id_fkey')
    )
    # ### end Alembic commands ###
